# Generated by Django 3.0.5 on 2020-07-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200713_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='team',
            field=models.CharField(choices=[('Leads', 'Leads'), ('Software', 'Software'), ('Hardware', 'Hardware'), ('Research', 'Research'), ('Outreach', 'Outreach')], max_length=200, null=True),
        ),
    ]
